esphome:
  name: smoke-x-gateway
  friendly_name: Smoke X Gateway

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# External component
external_components:
  - source: github://fastbytes/smoke-x-component
    components: [ smoke_x ]

# SPI for LoRa
spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

# Smoke X component
smoke_x:
  id: smoke_x_receiver
  cs_pin: GPIO8
  lora_rst_pin: GPIO12
  lora_busy_pin: GPIO13
  lora_dio1_pin: GPIO14

# Basic sensors for testing
text_sensor:
  - platform: smoke_x
    smoke_x_id: smoke_x_receiver
    device_id:
      name: "Smoke X Device ID"
    units:
      name: "Smoke X Units"

binary_sensor:
  - platform: smoke_x
    smoke_x_id: smoke_x_receiver
    synced:
      name: "Smoke X Synced"

sensor:
  - platform: smoke_x
    smoke_x_id: smoke_x_receiver
    probe_index: 0
    temperature:
      name: "Probe 1 Temperature"
